#not complete. Plan to use this instead of various dot config file.

---
location:
  path: ~/.aka/.location
global:
  path: ~/.aka/.global
groups:
  path: ~/.aka/groups
remote:
  path: ~/.aka/remote
history:
  path: ~/.aka/.location
location:
  path: ~/.aka/.location
location:
  path: ~/.aka/.location
